"""
Field-Level Payload Encryption (FLE) for Python Backend.

AES-256-GCM application-layer encryption and decryption matching the
exact wire format generated by the Web Crypto API on frontend and Deno edge:
enc:v1:<base64_iv>:<base64_ciphertext>:<base64_tag>
"""

import os
import base64
import hashlib
from typing import Any, Dict, List, Optional
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

FLE_PREFIX = "enc:v1:"
DEFAULT_APP_SALT = b"bizsprout-fle-salt-2026"
DEFAULT_SECRET = "bizsprout-payload-encryption-default-key-v1"

def derive_fle_key(passphrase: Optional[str] = None) -> bytes:
    """
    Derives a 256-bit (32-byte) AES-GCM key using PBKDF2-HMAC-SHA256,
    matching the Web Crypto key derivation in frontend & edge functions.
    """
    secret = passphrase or os.getenv("PAYLOAD_ENCRYPTION_KEY") or DEFAULT_SECRET
    return hashlib.pbkdf2_hmac(
        "sha256",
        secret.encode("utf-8"),
        DEFAULT_APP_SALT,
        iterations=100_000,
        dklen=32,
    )

def is_encrypted_field(value: Any) -> bool:
    """
    Checks if a given string is in the FLE format.
    """
    return isinstance(value, str) and value.startswith(FLE_PREFIX)

def encrypt_sensitive_field(plaintext: str, passphrase: Optional[str] = None) -> str:
    """
    Encrypts a plaintext string into the standardized wire format:
    enc:v1:<base64_iv>:<base64_ciphertext>:<base64_tag>
    """
    if not plaintext or not isinstance(plaintext, str):
        return plaintext

    key = derive_fle_key(passphrase)
    aesgcm = AESGCM(key)
    iv = os.urandom(12)  # 96-bit IV
    
    # AESGCM.encrypt appends the 16-byte authentication tag to the ciphertext
    encrypted = aesgcm.encrypt(iv, plaintext.encode("utf-8"), None)
    ciphertext = encrypted[:-16]
    tag = encrypted[-16:]

    iv_b64 = base64.b64encode(iv).decode("ascii")
    ciphertext_b64 = base64.b64encode(ciphertext).decode("ascii")
    tag_b64 = base64.b64encode(tag).decode("ascii")

    return f"{FLE_PREFIX}{iv_b64}:{ciphertext_b64}:{tag_b64}"

def decrypt_sensitive_field(encrypted_str: str, passphrase: Optional[str] = None) -> str:
    """
    Decrypts an FLE-encrypted string value.
    If the value is not encrypted, returns it unchanged for backwards compatibility.
    """
    if not is_encrypted_field(encrypted_str):
        return encrypted_str

    try:
        raw = encrypted_str[len(FLE_PREFIX):]
        parts = raw.split(":")
        if len(parts) != 3:
            return encrypted_str

        iv_b64, ciphertext_b64, tag_b64 = parts
        iv = base64.b64decode(iv_b64)
        ciphertext = base64.b64decode(ciphertext_b64)
        tag = base64.b64decode(tag_b64)

        key = derive_fle_key(passphrase)
        aesgcm = AESGCM(key)
        # AESGCM expects ciphertext + tag
        combined = ciphertext + tag
        decrypted_bytes = aesgcm.decrypt(iv, combined, None)
        return decrypted_bytes.decode("utf-8")
    except Exception as err:
        # Fallback to returning original string on decryption failure
        return encrypted_str

def decrypt_payload_fields(payload: Dict[str, Any], sensitive_keys: List[str], passphrase: Optional[str] = None) -> Dict[str, Any]:
    """
    Decrypts specified sensitive keys in a dictionary payload in place.
    """
    result = dict(payload)
    for key in sensitive_keys:
        if key in result and isinstance(result[key], str) and is_encrypted_field(result[key]):
            result[key] = decrypt_sensitive_field(result[key], passphrase)
    return result
